[package]
name = "runtime_demo"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
pollster.workspace = true
ui-core = { path = "../../crates/ui-core" }
ui-renderer = { path = "../../crates/ui-renderer" }
ui-runtime = { path = "../../crates/ui-runtime" }
ui-text = { path = "../../crates/ui-text" }
ui-window = { path = "../../crates/ui-window" }
wgpu.workspace = true
winit.workspace = true
